#!/bin/sh
# Copyright (C) 2004-2017 Soner Tari
#
# This file is part of UTMFW.
#
# UTMFW is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# UTMFW is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with UTMFW.  If not, see <http://www.gnu.org/licenses/>.

ARCH=amd64

ROOT_PATH=$(pwd)
VERSION='5.9'
SUBVERSION=_$(date +%Y%m%d)
VMAJ=${VERSION%%\.*}
VMIN=${VERSION##*\.}

TMP=tmp

SITE_DIR=site
SITE_CONTENTS="install.site install.sub root.mail etc"
SITE_FILE=site${VMAJ}${VMIN}.tgz

PROJECT_NAME=utmfw

LOCALE_PATH=locale
LOCALES_LIST="tr_TR sp_SP ru_RU zh_CN nl_NL fr_FR"

WEBIF=webif
WEBIF_FILE=utmfw-$WEBIF-${VMAJ}.${VMIN}.tar.gz

CONFIG=config
CONFIG_FILE=utmfw-$CONFIG-${VMAJ}.${VMIN}.tar.gz

PKG_PATH=packages

CD_PATH=cd/${ARCH}
INSTALL_SETS_PATH=${VERSION}/${ARCH}
BOOT_IMG=$INSTALL_SETS_PATH/cdbr
ISO_FILE=utmfw${VMAJ}${VMIN}${SUBVERSION}_${ARCH}.iso
SYS_ID="OpenBSD ${VERSION} ${ARCH}"
VOL_ID="UTMFW ${VERSION}${SUBVERSION} ${ARCH}"
PREP_ID="Soner Tari <sonertari@gmail.org>"
PUBLISH_ID="Copyright (C) 2017 Soner Tari, The UTMFW project"
APP_ID="UTMFW is a UTM firewall running on OpenBSD ${VERSION}"

echo $SYS_ID
echo $VOL_ID
echo $APP_ID
echo "========================="

echo "Cloning $PROJECT_NAME git repo:"

mkdir $ROOT_PATH/$TMP/
cd $ROOT_PATH/$TMP/
rm -rf .
git clone $ROOT_PATH

echo "Generating gettext translations:"

for locale in $LOCALES_LIST; do
	cd $ROOT_PATH/$TMP/$PROJECT_NAME/src/View/$LOCALE_PATH/$locale/LC_MESSAGES
	msgfmt -o utmfw.mo utmfw.po
done

echo "Generating source documention:"

cd $ROOT_PATH/$TMP/$PROJECT_NAME
doxygen Doxyfile

echo "Creating $WEBIF package: $WEBIF_FILE"

cd $ROOT_PATH/$TMP/$PROJECT_NAME
rm -rf $PROJECT_NAME
mv src $PROJECT_NAME
tar czf $ROOT_PATH/$TMP/$WEBIF_FILE $PROJECT_NAME
ln -fs $ROOT_PATH/$TMP/$WEBIF_FILE $ROOT_PATH/$CD_PATH/$PKG_PATH/$WEBIF_FILE

echo "Creating $CONFIG package: $CONFIG_FILE"

cd $ROOT_PATH/$TMP/$PROJECT_NAME
tar czf $ROOT_PATH/$TMP/$CONFIG_FILE $CONFIG
ln -fs $ROOT_PATH/$TMP/$CONFIG_FILE $ROOT_PATH/$CD_PATH/$PKG_PATH/$CONFIG_FILE

echo "Creating site install set: $SITE_FILE"

cd $ROOT_PATH/$SITE_DIR
rm -f *.tgz
tar czhf $SITE_FILE $SITE_CONTENTS
ln -fs $ROOT_PATH/$SITE_DIR/$SITE_FILE $ROOT_PATH/$CD_PATH/$INSTALL_SETS_PATH/$SITE_FILE

echo "Creating CD image: $ISO_FILE"

cd $ROOT_PATH
mkhybrid -f -l -T -r -L \
	-c boot.catalog \
	-sysid "$SYS_ID" \
	-p "$PREP_ID" \
	-P "$PUBLISH_ID" \
	-V "$VOL_ID" \
	-A "$APP_ID" \
	-b $BOOT_IMG \
	-o $ISO_FILE \
	$CD_PATH
