#!/bin/sh
# Copyright (C) 2004-2021 Soner Tari
#
# This file is part of UTMFW.
#
# UTMFW is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# UTMFW is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with UTMFW.  If not, see <http://www.gnu.org/licenses/>.

ARCH=amd64

add_platform_site_files() {
}

EXCLUDE_FROM_SHA256="boot.catalog SHA256 SHA256.sig"

. ./meta/create

BOOT_CATALOG=$INSTALL_SETS_PATH/boot.catalog
BOOT_IMG=$INSTALL_SETS_PATH/cdbr
ISO_FILE=utmfw${VMAJ}${VMIN}${SUBVERSION}_${ARCH}.iso

echo "Creating CD image: $ISO_FILE"

cd $ROOT_PATH
mkhybrid -f -l -T -r -L \
	-c $BOOT_CATALOG \
	-sysid "$SYS_ID" \
	-p "$PREP_ID" \
	-P "$PUBLISH_ID" \
	-V "$VOL_ID" \
	-A "$APP_ID" \
	-b $BOOT_IMG \
	-o $ISO_FILE \
	$CD_PATH
